# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
      - id: validate-toml
      - id: no-go-testing

  # Optional golangci-lint (may fail due to Go version compatibility)
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.62.2
    hooks:
      - id: golangci-lint
        args: [--fast, --timeout=5m]
        continue-on-error: true

  # Lightweight alternatives
  - repo: local
    hooks:
      - id: revive
        name: Run revive
        entry: revive
        language: golang
        types: [go]
        additional_dependencies: [github.com/mgechev/revive]
        
      - id: errcheck
        name: Run errcheck
        entry: errcheck
        language: golang
        types: [go]
        additional_dependencies: [github.com/kisielk/errcheck]