name: Code Quality Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    - name: Run go vet
      run: go vet ./...
    
    - name: Run go fmt check
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "以下文件需要格式化："
          gofmt -s -l .
          exit 1
        fi
    
    - name: Check go mod tidy
      run: |
        go mod tidy
        if [ -n "$(git status --porcelain go.mod go.sum)" ]; then
          echo "go.mod 或 go.sum 有未提交的更改"
          git diff go.mod go.sum
          exit 1
        fi
    
    - name: Run tests
      run: go test -v -race ./...
    
    # 运行轻量级代码质量检查工具
    - name: Install and run revive
      run: |
        go install github.com/mgechev/revive@latest
        revive ./...
    
    - name: Install and run errcheck
      run: |
        go install github.com/kisielk/errcheck@latest
        errcheck ./...